version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_username
      MYSQL_PASSWORD: your_mysql_password

<<<<<<< HEAD
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    ports:
      - "8080:80"
=======
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      
"8000:80"
  environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: your_mysql_username
    WORDPRESS_DB_PASSWORD: your_mysql_password
    WORDPRESS_DB_NAME: your_database_name
>>>>>>> Otman
